# Generated by Django 2.2.1 on 2019-10-04 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('SUV', 'SUV')], default='car', max_length=6)),
                ('seats', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reserved', models.BooleanField(default=False)),
                ('rented', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
