# Generated by Django 2.2.1 on 2019-11-21 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0004_auto_20191107_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
