# Generated by Django 2.2.1 on 2019-11-22 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0005_auto_20191121_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_make',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
