# Generated by Django 2.2.1 on 2019-11-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0006_auto_20191122_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Sport', 'Sport'), ('Luxury', 'Luxury')], default='Standard', max_length=9),
        ),
    ]
