# Generated by Django 2.2.1 on 2019-11-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0007_vehicle_vehicle_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='reserved_by',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Sport', 'Sport'), ('Luxury', 'Luxury'), ('All', 'All')], default='Standard', max_length=9),
        ),
    ]
