# Generated by Django 2.2.1 on 2019-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0008_auto_20191123_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_make',
            field=models.CharField(max_length=14),
        ),
    ]
