# Generated by Django 2.2.1 on 2020-10-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0010_auto_20191128_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('suv', 'SUV')], default='car', max_length=6),
        ),
    ]
